package edu.miu.cs525.finalproject.creditcard.ui;
/*
		A basic implementation of the JDialog class.
*/

import edu.miu.cs525.finalproject.creditcard.service.CreditCardServiceImpl;
import edu.miu.cs525.finalproject.creditcard.service.CreditReportServiceImpl;
import edu.miu.cs525.finalproject.framework.service.AccountService;
import edu.miu.cs525.finalproject.framework.service.ReportService;

import javax.swing.*;
import java.awt.*;

public class JDialogGenBill extends JDialog {
    String billstring;


    ReportService reportService;

    public JDialogGenBill(Frame parent) {
        super(parent);
        reportService = new CreditReportServiceImpl();

        // This code is automatically generated by Visual Cafe when you add
        // components to the visual environment. It instantiates and initializes
        // the components. To modify the code, only use code syntax that matches
        // what Visual Cafe can generate, or Visual Cafe may be unable to back
        // parse your Java file into its visual environment.
        //{{INIT_CONTROLS
        getContentPane().setLayout(null);

        setSize(405,340);
        setLocationRelativeTo(null);
        setVisible(false);

        getContentPane().add(JScrollPane1);
        JScrollPane1.setBounds(24,24,358,240);
        JScrollPane1.getViewport().add(JTextField1);
        JTextField1.setBounds(0,0,355,237);
        JButton_OK.setText("OK");
        JButton_OK.setActionCommand("OK");
        getContentPane().add(JButton_OK);
        JButton_OK.setBounds(156,276,96,24);


        // generate the string for the monthly bill
        billstring = reportService.generateReport();
        JTextField1.setText(billstring);

        //{{REGISTER_LISTENERS
        SymAction lSymAction = new SymAction();
        JButton_OK.addActionListener(lSymAction);
        //}}
    }

    public JDialogGenBill() {
        this((Frame) null);
    }


    //{{DECLARE_CONTROLS



    JScrollPane JScrollPane1 = new JScrollPane();
//    JTextField JTextField1 = new JTextField();
    JTextArea JTextField1 = new JTextArea();
    JButton JButton_OK = new JButton();
    //}}


    class SymAction implements java.awt.event.ActionListener {
        public void actionPerformed(java.awt.event.ActionEvent event) {
            Object object = event.getSource();
            if (object == JButton_OK)
                JButtonOK_actionPerformed(event);
        }
    }

    void JButtonOK_actionPerformed(java.awt.event.ActionEvent event) {
        dispose();

    }
}
